server:
  port: 8762

spring:
  application:
    name: eureka-server-ha # 应用名称，会在Eureka中显示


# eureka 配置
#一共有四个部分配置
#dashboard： web 控制台配置
#server: 服务端配置
#client: 客户端配置
#instance： 实例配置
eureka:
  instance:
    hostname: eureka-server1
  client:
    register-with-eureka: true # 是否注册自己的信息到EurekaServer，默认是true
    fetch-registry: true # 是否拉取其它服务的信息，默认是true
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://eureka-server2:8763/eureka
