server:
  port: 9000


spring:
  application:
    name: eureka-consumer # 应用名称，会在Eureka中显示


eureka:
  instance:
    hostname: localhost
  client:
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      #defaultZone: http://eureka-server1:8762/eureka,http://eureka-server2:8763/eureka
      defaultZone: http://localhost:8761/eureka

#EUREKA-PROVIDER:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

ribbon:
  ConnectTimeout: 6000 # 连接超时时间(ms) 默认1s
  ReadTimeout: 3000 # 通信超时时间(ms)默认1s
#  OkToRetryOnAllOperations: true # 是否对所有操作重试
#  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
#  MaxAutoRetries: 1 # 同一实例的重试次数
logging:
  level:
    com.itheima: debug
# 开启feign对hystrix的支持
feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能